/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.table.DefaultTableModel;
import clases.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author CESAR DIAZ MARADIAGA
 */
public class IMenu extends javax.swing.JFrame {
    String id;
    private int x = 0, y = 0;
    DefaultTableModel modelo;
    Clientes clientes;
    Conexiondb conexion;
    

    /**
     * Creates new form IMenu
     */
    public IMenu() {
        this.clientes = new Clientes();
        this.conexion = new Conexiondb();
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarClientes("");
        Deshabilitar();
        id="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        EditarCliente = new javax.swing.JMenuItem();
        BorrarCliente = new javax.swing.JMenuItem();
        pnlContenedor = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlVentas = new javax.swing.JPanel();
        pnlReportes = new javax.swing.JPanel();
        pnlClientes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombresCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApellidosCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        btnNuevorClientes = new javax.swing.JButton();
        btnGuardarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pnlInventario = new javax.swing.JPanel();
        pnlCreditos = new javax.swing.JPanel();
        pnlEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnRestablecer = new javax.swing.JButton();
        pnlMenuLateral = new javax.swing.JPanel();
        btnVentas = new javax.swing.JPanel();
        lblIconVentas = new javax.swing.JLabel();
        lblMenuVentas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReportes = new javax.swing.JPanel();
        lblIconReportes = new javax.swing.JLabel();
        lblMenuReportes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnClientes = new javax.swing.JPanel();
        lblIconClientes = new javax.swing.JLabel();
        lblMenuClientes = new javax.swing.JLabel();
        btnInventario = new javax.swing.JPanel();
        lblIconIventario = new javax.swing.JLabel();
        lblMenuInventario = new javax.swing.JLabel();
        btnCreditos = new javax.swing.JPanel();
        lblIconCreditos = new javax.swing.JLabel();
        lblMenuCreditos = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnCerrarSesion = new javax.swing.JPanel();
        lblIconCerrarSesion = new javax.swing.JLabel();
        lblMenuCerrarSesion = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JPanel();
        lblIconUsuario = new javax.swing.JLabel();
        lblMenuUsuarios = new javax.swing.JLabel();

        EditarCliente.setText("Editar");
        EditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarClienteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(EditarCliente);

        BorrarCliente.setText("Borrar");
        BorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarClienteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(BorrarCliente);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 222, 171), 2));
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new java.awt.CardLayout());

        pnlVentas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlVentasLayout = new javax.swing.GroupLayout(pnlVentas);
        pnlVentas.setLayout(pnlVentasLayout);
        pnlVentasLayout.setHorizontalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        pnlVentasLayout.setVerticalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlVentas, "card2");

        pnlReportes.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlReportes, "card3");

        pnlClientes.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(227, 236, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Nuevo Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Nombres :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        txtNombresCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNombresCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombresCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 194, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Apellidos :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Telefono  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Dirección :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtApellidosCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtApellidosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 194, -1));

        txtTelefonoCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 194, -1));

        txtDireccionCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 194, -1));

        btnNuevorClientes.setBackground(new java.awt.Color(0, 166, 192));
        btnNuevorClientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnNuevorClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevorClientes.setText("Nuevo");
        btnNuevorClientes.setBorder(null);
        btnNuevorClientes.setBorderPainted(false);
        btnNuevorClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevorClientes.setFocusPainted(false);
        btnNuevorClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevorClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevorClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 100, 40));

        btnGuardarCliente.setBackground(new java.awt.Color(0, 166, 192));
        btnGuardarCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCliente.setText("Guardar");
        btnGuardarCliente.setBorder(null);
        btnGuardarCliente.setBorderPainted(false);
        btnGuardarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCliente.setFocusPainted(false);
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 100, 40));

        btnActualizarCliente.setBackground(new java.awt.Color(0, 166, 192));
        btnActualizarCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarCliente.setText("Actualizar");
        btnActualizarCliente.setBorder(null);
        btnActualizarCliente.setBorderPainted(false);
        btnActualizarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarCliente.setFocusPainted(false);
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 100, 40));

        jScrollPane1.setBackground(new java.awt.Color(64, 64, 64));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tblClientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Cliente", "Nombre", "Apellidos", "Telefono", "Direccion"
            }
        ));
        tblClientes.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tblClientes);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Buscar :");

        txtBuscarCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtBuscarCliente.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscarClienteCaretUpdate(evt);
            }
        });
        txtBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarClienteActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man_user_client_16776.png"))); // NOI18N

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlClientesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlClientesLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(70, 70, 70)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pnlPrincipal.add(pnlClientes, "card4");

        pnlInventario.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
        pnlInventario.setLayout(pnlInventarioLayout);
        pnlInventarioLayout.setHorizontalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        pnlInventarioLayout.setVerticalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlInventario, "card5");

        pnlCreditos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlCreditosLayout = new javax.swing.GroupLayout(pnlCreditos);
        pnlCreditos.setLayout(pnlCreditosLayout);
        pnlCreditosLayout.setHorizontalGroup(
            pnlCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        pnlCreditosLayout.setVerticalGroup(
            pnlCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlCreditos, "card6");

        pnlContenedor.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 93, 1054, 513));

        pnlEncabezado.setBackground(new java.awt.Color(64, 64, 64));
        pnlEncabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Farmacia Ponce");
        pnlEncabezado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error_1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlEncabezado.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 30, 30));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/maximizar.png"))); // NOI18N
        btnMaximizar.setBorder(null);
        btnMaximizar.setBorderPainted(false);
        btnMaximizar.setContentAreaFilled(false);
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.setFocusPainted(false);
        btnMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizarActionPerformed(evt);
            }
        });
        pnlEncabezado.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlEncabezado.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 30, 30));

        btnRestablecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/maximizar.png"))); // NOI18N
        btnRestablecer.setBorder(null);
        btnRestablecer.setContentAreaFilled(false);
        btnRestablecer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });
        pnlEncabezado.add(btnRestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 30));

        pnlContenedor.add(pnlEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1256, 90));

        pnlMenuLateral.setBackground(new java.awt.Color(64, 64, 64));
        pnlMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentas.setBackground(new java.awt.Color(64, 64, 64));
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
        });

        lblIconVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito-de-compras (1).png"))); // NOI18N

        lblMenuVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMenuVentas.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuVentas.setText("Ventas");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/charts (1).png"))); // NOI18N

        javax.swing.GroupLayout btnVentasLayout = new javax.swing.GroupLayout(btnVentas);
        btnVentas.setLayout(btnVentasLayout);
        btnVentasLayout.setHorizontalGroup(
            btnVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVentasLayout.createSequentialGroup()
                .addGroup(btnVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnVentasLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4))
                    .addGroup(btnVentasLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblIconVentas)
                        .addGap(36, 36, 36)
                        .addComponent(lblMenuVentas)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btnVentasLayout.setVerticalGroup(
            btnVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVentasLayout.createSequentialGroup()
                .addGroup(btnVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnVentasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMenuVentas)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenuLateral.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 200, 50));

        btnReportes.setBackground(new java.awt.Color(64, 64, 64));
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });

        lblIconReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/charts (1).png"))); // NOI18N

        lblMenuReportes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMenuReportes.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuReportes.setText("Reportes");

        javax.swing.GroupLayout btnReportesLayout = new javax.swing.GroupLayout(btnReportes);
        btnReportes.setLayout(btnReportesLayout);
        btnReportesLayout.setHorizontalGroup(
            btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReportesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblIconReportes)
                .addGap(35, 35, 35)
                .addComponent(lblMenuReportes)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        btnReportesLayout.setVerticalGroup(
            btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnReportesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblMenuReportes)
                .addContainerGap())
        );

        pnlMenuLateral.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 50));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        pnlMenuLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 10));

        btnClientes.setBackground(new java.awt.Color(64, 64, 64));
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });

        lblIconClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario (0).png"))); // NOI18N

        lblMenuClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMenuClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuClientes.setText("Clientes");

        javax.swing.GroupLayout btnClientesLayout = new javax.swing.GroupLayout(btnClientes);
        btnClientes.setLayout(btnClientesLayout);
        btnClientesLayout.setHorizontalGroup(
            btnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClientesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblIconClientes)
                .addGap(35, 35, 35)
                .addComponent(lblMenuClientes)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        btnClientesLayout.setVerticalGroup(
            btnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnClientesLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(lblMenuClientes)
                .addContainerGap())
            .addComponent(lblIconClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenuLateral.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 50));

        btnInventario.setBackground(new java.awt.Color(64, 64, 64));
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventarioMouseClicked(evt);
            }
        });

        lblIconIventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crecimiento.png"))); // NOI18N

        lblMenuInventario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMenuInventario.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuInventario.setText("Inventario");

        javax.swing.GroupLayout btnInventarioLayout = new javax.swing.GroupLayout(btnInventario);
        btnInventario.setLayout(btnInventarioLayout);
        btnInventarioLayout.setHorizontalGroup(
            btnInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInventarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblIconIventario)
                .addGap(32, 32, 32)
                .addComponent(lblMenuInventario)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btnInventarioLayout.setVerticalGroup(
            btnInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuInventario)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(lblIconIventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenuLateral.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 50));

        btnCreditos.setBackground(new java.awt.Color(64, 64, 64));
        btnCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreditosMouseClicked(evt);
            }
        });

        lblIconCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/creditos (1).png"))); // NOI18N

        lblMenuCreditos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMenuCreditos.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuCreditos.setText("Creditos");

        javax.swing.GroupLayout btnCreditosLayout = new javax.swing.GroupLayout(btnCreditos);
        btnCreditos.setLayout(btnCreditosLayout);
        btnCreditosLayout.setHorizontalGroup(
            btnCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCreditosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblIconCreditos)
                .addGap(36, 36, 36)
                .addComponent(lblMenuCreditos)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btnCreditosLayout.setVerticalGroup(
            btnCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCreditosLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(lblMenuCreditos)
                .addContainerGap())
            .addComponent(lblIconCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenuLateral.add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 50));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        pnlMenuLateral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 10));

        btnCerrarSesion.setBackground(new java.awt.Color(64, 64, 64));
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });

        lblIconCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida (1).png"))); // NOI18N

        lblMenuCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMenuCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuCerrarSesion.setText("Cerrar Sesión");

        javax.swing.GroupLayout btnCerrarSesionLayout = new javax.swing.GroupLayout(btnCerrarSesion);
        btnCerrarSesion.setLayout(btnCerrarSesionLayout);
        btnCerrarSesionLayout.setHorizontalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblIconCerrarSesion)
                .addGap(18, 18, 18)
                .addComponent(lblMenuCerrarSesion)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnCerrarSesionLayout.setVerticalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuCerrarSesion)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(lblIconCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenuLateral.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 50));

        btnUsuarios.setBackground(new java.awt.Color(64, 64, 64));
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });

        lblIconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        lblMenuUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMenuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuUsuarios.setText("Usuarios");

        javax.swing.GroupLayout btnUsuariosLayout = new javax.swing.GroupLayout(btnUsuarios);
        btnUsuarios.setLayout(btnUsuariosLayout);
        btnUsuariosLayout.setHorizontalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuariosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblIconUsuario)
                .addGap(40, 40, 40)
                .addComponent(lblMenuUsuarios)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        btnUsuariosLayout.setVerticalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuariosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMenuUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblIconUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenuLateral.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 50));

        pnlContenedor.add(pnlMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 92, 200, 515));

        getContentPane().add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked
        btnVentas.setBackground(new java.awt.Color(255, 255, 255));
        lblMenuVentas.setForeground(new java.awt.Color(0, 222, 171));

        btnReportes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuReportes.setForeground(new java.awt.Color(255, 255, 255));

        btnClientes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuClientes.setForeground(new java.awt.Color(255, 255, 255));

        btnInventario.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuInventario.setForeground(new java.awt.Color(255, 255, 255));

        btnCreditos.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCreditos.setForeground(new java.awt.Color(255, 255, 255));

        btnCerrarSesion.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));

        btnUsuarios.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuUsuarios.setForeground(new java.awt.Color(255, 255, 255));

    }//GEN-LAST:event_btnVentasMouseClicked

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        lblMenuReportes.setForeground(new java.awt.Color(0, 222, 171));

        btnVentas.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuVentas.setForeground(new java.awt.Color(255, 249, 252));

        btnClientes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuClientes.setForeground(new java.awt.Color(255, 255, 255));

        btnInventario.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuInventario.setForeground(new java.awt.Color(255, 255, 255));

        btnCreditos.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCreditos.setForeground(new java.awt.Color(255, 255, 255));

        btnCerrarSesion.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));

        btnUsuarios.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnReportesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizarActionPerformed
        this.setExtendedState(MAXIMIZED_BOTH);
        btnMaximizar.setVisible(false);
        btnRestablecer.setVisible(true);
    }//GEN-LAST:event_btnMaximizarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        this.setSize(1260, 610);
        btnRestablecer.setVisible(false);
        btnMaximizar.setVisible(true);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        lblMenuClientes.setForeground(new java.awt.Color(0, 222, 171));

        btnReportes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuReportes.setForeground(new java.awt.Color(255, 255, 255));

        btnVentas.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuVentas.setForeground(new java.awt.Color(255, 255, 255));

        btnInventario.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuInventario.setForeground(new java.awt.Color(255, 255, 255));

        btnCreditos.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCreditos.setForeground(new java.awt.Color(255, 255, 255));

        btnCerrarSesion.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));

        btnUsuarios.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuUsuarios.setForeground(new java.awt.Color(255, 255, 255));

        pnlClientes.setVisible(true);
        pnlVentas.setVisible(false);
        pnlReportes.setVisible(false);
        pnlInventario.setVisible(false);
        pnlCreditos.setVisible(false);
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseClicked
        btnInventario.setBackground(new java.awt.Color(255, 255, 255));
        lblMenuInventario.setForeground(new java.awt.Color(0, 222, 171));

        btnReportes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuReportes.setForeground(new java.awt.Color(255, 255, 255));

        btnVentas.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuVentas.setForeground(new java.awt.Color(255, 255, 255));

        btnClientes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuClientes.setForeground(new java.awt.Color(255, 255, 255));

        btnCreditos.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCreditos.setForeground(new java.awt.Color(255, 255, 255));

        btnCerrarSesion.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));

        btnUsuarios.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnInventarioMouseClicked

    private void btnCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditosMouseClicked
        btnCreditos.setBackground(new java.awt.Color(255, 255, 255));
        lblMenuCreditos.setForeground(new java.awt.Color(0, 222, 171));

        btnReportes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuReportes.setForeground(new java.awt.Color(255, 255, 255));

        btnVentas.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuVentas.setForeground(new java.awt.Color(255, 255, 255));

        btnInventario.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuInventario.setForeground(new java.awt.Color(255, 255, 255));

        btnClientes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuClientes.setForeground(new java.awt.Color(255, 255, 255));

        btnCerrarSesion.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));

        btnUsuarios.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnCreditosMouseClicked

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        lblMenuCerrarSesion.setForeground(new java.awt.Color(0, 222, 171));

        btnReportes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuReportes.setForeground(new java.awt.Color(255, 255, 255));

        btnVentas.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuVentas.setForeground(new java.awt.Color(255, 255, 255));

        btnInventario.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuInventario.setForeground(new java.awt.Color(255, 255, 255));

        btnCreditos.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCreditos.setForeground(new java.awt.Color(255, 255, 255));

        btnClientes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuClientes.setForeground(new java.awt.Color(255, 255, 255));

        btnUsuarios.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        ILogin login = new ILogin();
        this.dispose();
        login.setVisible(true);
        
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        lblMenuUsuarios.setForeground(new java.awt.Color(0, 222, 171));

        btnReportes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuReportes.setForeground(new java.awt.Color(255, 255, 255));

        btnVentas.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuVentas.setForeground(new java.awt.Color(255, 255, 255));

        btnInventario.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuInventario.setForeground(new java.awt.Color(255, 255, 255));

        btnCreditos.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCreditos.setForeground(new java.awt.Color(255, 255, 255));

        btnCerrarSesion.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));

        btnClientes.setBackground(new java.awt.Color(64, 64, 64));
        lblMenuClientes.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        String nombres = "", apellidos = "", telefono = "", direccion = "";
        nombres = txtNombresCliente.getText();
        apellidos = txtApellidosCliente.getText();
        telefono = txtTelefonoCliente.getText();
        direccion = txtDireccionCliente.getText();
        clientes.Guardar(nombres, apellidos, telefono, direccion);
        MostrarClientes("");
        Limpiar();
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void txtBuscarClienteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscarClienteCaretUpdate
        String Buscar = txtBuscarCliente.getText();
        MostrarClientes(Buscar);
    }//GEN-LAST:event_txtBuscarClienteCaretUpdate

    private void txtBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarClienteActionPerformed
        
    }//GEN-LAST:event_txtBuscarClienteActionPerformed

    private void btnNuevorClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevorClientesActionPerformed
        Limpiar();
        Habilitar();
    }//GEN-LAST:event_btnNuevorClientesActionPerformed

    private void txtNombresClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresClienteActionPerformed
        //txtNombresCliente.transferFocus();
    }//GEN-LAST:event_txtNombresClienteActionPerformed

    private void txtApellidosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosClienteActionPerformed
        //txtApellidosCliente.transferFocus();
    }//GEN-LAST:event_txtApellidosClienteActionPerformed

    private void txtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteActionPerformed
        //txtTelefonoCliente.transferFocus();
    }//GEN-LAST:event_txtTelefonoClienteActionPerformed

    private void EditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarClienteActionPerformed
       int filaSeleccionada = 0;
       String id;
       try
       {
           filaSeleccionada = tblClientes.getSelectedRow();
           if(filaSeleccionada == -1)
           {
               JOptionPane.showMessageDialog(null, "Seleccione una Fila","Advertencia", JOptionPane.WARNING_MESSAGE);
           }
           else{
               modelo = (DefaultTableModel) tblClientes.getModel();
               id=(String) modelo.getValueAt(filaSeleccionada, 0);
               Habilitar();
               Limpiar();
               ModificarClientes(id);
               btnGuardarCliente.setEnabled(false);
               btnActualizarCliente.setEnabled(true);
           }
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
       
    }//GEN-LAST:event_EditarClienteActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        clientes.Actualzar(id, txtNombresCliente.getText(), txtApellidosCliente.getText(), txtTelefonoCliente.getText(), txtDireccionCliente.getText());
        MostrarClientes("");
        btnGuardarCliente.setEnabled(true);
        btnActualizarCliente.setEnabled(false);
        Limpiar();
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void BorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarClienteActionPerformed
        int filaSelect;
        String id;
        try
        {
            filaSelect = tblClientes.getSelectedRow();
            if(filaSelect==-1)
            {
                JOptionPane.showMessageDialog(null,"Seleccione una fila","Advertencia",JOptionPane.WARNING_MESSAGE);
            }else{
                int confirmar = JOptionPane.showConfirmDialog(null, "Seguro que Quires Borrar Este Cliente", "Informacion", JOptionPane.OK_CANCEL_OPTION);
                if(confirmar == JOptionPane.YES_OPTION)
                {
                    modelo = (DefaultTableModel) tblClientes.getModel();
                    id =(String) modelo.getValueAt(filaSelect, 0);
                    clientes.Eliminar(id);
                    MostrarClientes("");
                }
            }
            
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_BorrarClienteActionPerformed

    public void ModificarClientes(String id)
    {
        String nombres="", apellidos="", telefono="", direccion="";
        Connection cn = conexion.Conexion();
        String consulta = "SELECT nombres, apellidos, telefono, direccion FROM clientes WHERE id ="+id;
        try
        {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while(rs.next())
            {
                nombres=rs.getString("nombres");
                apellidos=rs.getString("apellidos");
                telefono=rs.getString("telefono");
                direccion=rs.getString("direccion");
            }          
        }catch(SQLException e)
        {
            
        }
        txtNombresCliente.setText(nombres);
        txtApellidosCliente.setText(apellidos);
        txtTelefonoCliente.setText(telefono);
        txtDireccionCliente.setText(direccion);
        this.id=id;
    }
    
    public void MostrarClientes(String Buscar)
    {
        tblClientes.setModel(clientes.Consulta(Buscar));
    }
    
    public void Limpiar()
    {
        txtNombresCliente.setText("");
        txtApellidosCliente.setText("");
        txtTelefonoCliente.setText("");
        txtDireccionCliente.setText("");
    }
    public void Deshabilitar()
    {
        btnGuardarCliente.setEnabled(false);
        btnActualizarCliente.setEnabled(false);
        txtNombresCliente.setEnabled(false);
        txtApellidosCliente.setEnabled(false);
        txtTelefonoCliente.setEnabled(false);
        txtDireccionCliente.setEnabled(false);
    }
    public void Habilitar()
    {
        btnGuardarCliente.setEnabled(true);
        btnActualizarCliente.setEnabled(false);
        txtNombresCliente.setEnabled(true);
        txtApellidosCliente.setEnabled(true);
        txtTelefonoCliente.setEnabled(true);
        txtDireccionCliente.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BorrarCliente;
    private javax.swing.JMenuItem EditarCliente;
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JPanel btnCerrarSesion;
    private javax.swing.JPanel btnClientes;
    private javax.swing.JPanel btnCreditos;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JPanel btnInventario;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnNuevorClientes;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JPanel btnUsuarios;
    private javax.swing.JPanel btnVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblIconCerrarSesion;
    private javax.swing.JLabel lblIconClientes;
    private javax.swing.JLabel lblIconCreditos;
    private javax.swing.JLabel lblIconIventario;
    private javax.swing.JLabel lblIconReportes;
    private javax.swing.JLabel lblIconUsuario;
    private javax.swing.JLabel lblIconVentas;
    private javax.swing.JLabel lblMenuCerrarSesion;
    private javax.swing.JLabel lblMenuClientes;
    private javax.swing.JLabel lblMenuCreditos;
    private javax.swing.JLabel lblMenuInventario;
    private javax.swing.JLabel lblMenuReportes;
    private javax.swing.JLabel lblMenuUsuarios;
    private javax.swing.JLabel lblMenuVentas;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlCreditos;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JPanel pnlMenuLateral;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JPanel pnlVentas;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellidosCliente;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtNombresCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
